cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.37.5
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    devices:
      - /dev/kmsg:/dev/kmsg
    restart: always
    ports:
      - 8184:8080
    labels:
      org.label-schema.group: "monitoring"
